[tool.poetry]
name = "ewfs"
version = "0.1.0"
description = ""
authors = ["vrusso <vincentrusso1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
qiskit = "^2.2.2"
pylatexenc = "^2.10"
seaborn = "^0.13.2"
notebook = "7.4.7"
qiskit-aer = "^0.17.1"
jupyter = "^1.1.1"
networkx = "^3.3"
ipykernel = "^7.0.1"
qiskit-ibm-runtime = "^0.42.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.18.2"
pre-commit = "^4.3.0"
ruff = "^0.13.2"
pytest = "^8.4.2"

[tool.mypy]
files = ["ewfs/**/*.py"]
ignore_missing_imports = true   
follow_imports = "skip"

[tool.ruff]
line-length = 120
extend-exclude = ["*.ipynb"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
